services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "8000:8000"
    networks:
      - laravel

  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-files:/var/lib/mysql-files
    ports:
      - "3307:3306"
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge
